[package]
name = "open-gal"
version = "0.1.0"
authors = ["eeli1 <maierelias13@gmail.com>"]
edition = "2018"

[dependencies]
bool-algebra = { git = "https://github.com/eeli1/bool-algebra", version = "0.1.0" }
