[package]
name = "open_gal"
version = "0.1.0"
authors = ["eeli1 <39457447+eeli1@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cbindgen = "0.19.0"
